run:
  tests: true
  modules-download-mode: vendor
  relative-path-mode: gitroot
  build-tags: []

issues:
  exclude-dirs:
      - vendor

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      main:
        list-mode: lax
        allow: 
          - github.com/swaggo/gin-swagger
  gci:
    sections:
      - standard
      - prefix(github.com/mikhailshtv/stockLkBack)
      - default
    skip-generated: true
    custom-order: true
  gofumpt:
    extra-rules: true
    module-path: "github.com/mikhailshtv/stockLkBack"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

