
services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb_stocklk
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo_user
  #     MONGO_INITDB_ROOT_PASSWORD: mongo_pass
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  postgresql:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: stocklkback
      POSTGRES_PASSWORD: stocklkback
      POSTGRES_DB: stocklk
    ports:
      - "8082:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_stocklk
    restart: always
    ports:
      - "8081:6379"
    volumes:
      - redis_data:/data

volumes:
  # mongo_data:
  postgres_data:
  redis_data:
